import re

def generate_scenario_calls(input_text,
                            prefix_txt1="scenario_text_0074",
                            prefix_txt2="scenario_text_0004",
                            wts_value="0x08",   #adjusts speed of default
                            output_file="generated_calls.c"):

    # Find all scenario_text_XXXX identifiers
    pattern = r"static\s+s16\s+(scenario_text_[0-9A-Fa-f]+)\[\]"
    matches = re.findall(pattern, input_text)

    if not matches:
        print("No scenario_text entries found.")
        return

    lines = []

    for name in matches:
        line = (
            f"        TXT, (s32)&{prefix_txt1}, "
            f"TXT, (s32)&{prefix_txt2}, "
            f"TXT, (s32)&{name}, "
            f"STW, (s32)&D_801C7740_1C8340, "
            f"WTS, {wts_value}, "
            f"ESR, (s32)&func_8003F460_40060,"
        )
        lines.append(line)

    # Write to file
    with open(output_file, "w") as f:
        for line in lines:
            f.write(line + "\n")

    print(f"Generated {len(lines)} scenario calls to {output_file}")


# ------------------ INPUT BLOCK ------------------

input_block = """
static s16 scenario_text_0000[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0001[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0002[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0003[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0004[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0005[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0006[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0007[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0008[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0009[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000A[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000B[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000C[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000D[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000E[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_000F[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };

static s16 scenario_text_0100[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CTR_CLOSE_EM, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0101[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CTR_CLOSE_EM, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0102[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CTR_CLOSE_EM, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0103[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CTR_CLOSE_EM, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0104[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CTR_CLOSE_EM, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0105[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CTR_CLOSE_EM, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0106[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CTR_CLOSE_EM, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0107[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CTR_CLOSE_EM, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0108[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CTR_CLOSE_EM, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0109[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CTR_CLOSE_EM, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_010A[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_010B[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };

static s16 scenario_text_0200[] = { CTR_EM_YELLOW, CHR_K, CTR_CLOSE_EM, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0201[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CTR_CLOSE_EM, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0202[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CTR_CLOSE_EM, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0203[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CTR_CLOSE_EM, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0204[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CTR_CLOSE_EM, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0205[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CTR_CLOSE_EM, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0206[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0207[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0208[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0209[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020A[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020B[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020C[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020D[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020E[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_020F[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0210[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0211[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0212[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0213[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, CTR_CLOSE_EM, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0214[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CTR_CLOSE_EM, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0215[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CTR_CLOSE_EM, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0216[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CTR_CLOSE_EM, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0217[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0218[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0219[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CTR_CLOSE_EM, CHR_o, CTR_ENDLINE };
static s16 scenario_text_021A[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_0300[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CTR_CLOSE_EM, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0301[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CTR_CLOSE_EM, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0302[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CTR_CLOSE_EM, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0303[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CTR_CLOSE_EM, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0304[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0305[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0306[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, CHR_w, CTR_ENDLINE };
static s16 scenario_text_0307[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_0400[] = { CTR_EM_YELLOW, CHR_S, CTR_CLOSE_EM, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0401[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0402[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0403[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CTR_CLOSE_EM, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0404[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CTR_CLOSE_EM, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0405[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CTR_CLOSE_EM, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0406[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CTR_CLOSE_EM, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0407[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0408[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0409[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CTR_CLOSE_EM, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040A[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040B[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040C[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040D[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040E[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_040F[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0410[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0411[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CTR_CLOSE_EM, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0412[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0413[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0414[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0415[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0416[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0417[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0418[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CTR_CLOSE_EM, CHR_o, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0419[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CTR_CLOSE_EM, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_041A[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CTR_CLOSE_EM, CHR_a, CTR_ENDLINE };
static s16 scenario_text_041B[] = { CTR_EM_YELLOW, CHR_S, CHR_a, CHR_a, PCT_SPACE, CHR_g, CHR_o, CHR_r, CHR_a, CHR_n, PCT_SPACE, CHR_k, CHR_u, CHR_m, CHR_o, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_s, CHR_u, CHR_k, CHR_i, CHR_m, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, PCT_SPACE, CHR_h, CHR_o, CHR_r, CHR_a, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_0500[] = { CTR_EM_YELLOW, CHR_M, CTR_CLOSE_EM, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0501[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CTR_CLOSE_EM, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0502[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CTR_CLOSE_EM, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0503[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0504[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0505[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0506[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CTR_CLOSE_EM, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0507[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0508[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0509[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050A[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050B[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050C[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050D[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050E[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_050F[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0510[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CTR_CLOSE_EM, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0511[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0512[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0513[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0514[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0515[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0516[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0517[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_a, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0518[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CTR_CLOSE_EM, CHR_t, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0519[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CTR_CLOSE_EM, CHR_a, CTR_ENDLINE };
static s16 scenario_text_051A[] = { CTR_EM_YELLOW, CHR_M, CHR_i, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_k, CHR_u, CHR_r, CHR_u, PCT_SPACE, CHR_h, CHR_a, CHR_r, CHR_u, CHR_k, CHR_a, PCT_SPACE, CHR_s, CHR_o, CHR_r, CHR_a, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_k, CHR_a, CHR_n, CHR_a, CHR_t, CHR_a, CTR_CLOSE_EM, CTR_ENDLINE };


}
static s16 scenario_text_0600[] = { CTR_EM_YELLOW, CHR_T, CTR_CLOSE_EM, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0601[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CTR_CLOSE_EM, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0602[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CTR_CLOSE_EM, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0603[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0604[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0605[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CTR_CLOSE_EM, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0606[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CTR_CLOSE_EM, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0607[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CTR_CLOSE_EM, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0608[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CTR_CLOSE_EM, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0609[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CTR_CLOSE_EM, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060A[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CTR_CLOSE_EM, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060B[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CTR_CLOSE_EM, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060C[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060D[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060E[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CTR_CLOSE_EM, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_060F[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0610[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0611[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0612[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0613[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0614[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0615[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0616[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CTR_CLOSE_EM, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0617[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0618[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_0619[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_061A[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_061B[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_061C[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_m, CHR_o, CTR_ENDLINE };
static s16 scenario_text_061D[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CTR_CLOSE_EM, CHR_o, CTR_ENDLINE };
static s16 scenario_text_061E[] = { CTR_EM_YELLOW, CHR_T, CHR_a, CHR_t, CHR_o, CHR_e, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_m, CHR_e, CHR_t, CHR_a, CHR_i, PCT_SPACE, CHR_k, CHR_a, CHR_z, CHR_e, PCT_SPACE, CHR_n, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_r, CHR_a, CHR_s, CHR_a, CHR_r, CHR_e, CHR_t, CHR_e, PCT_SPACE, CHR_m, CHR_o, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_0700[] = { CTR_EM_YELLOW, CHR_J, CTR_CLOSE_EM, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0701[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CTR_CLOSE_EM, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0702[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CTR_CLOSE_EM, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0703[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CTR_CLOSE_EM, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0704[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, CTR_CLOSE_EM, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0705[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CTR_CLOSE_EM, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0706[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CTR_CLOSE_EM, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0707[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CTR_CLOSE_EM, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0708[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CTR_CLOSE_EM, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0709[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CTR_CLOSE_EM, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070A[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070B[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070C[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CTR_CLOSE_EM, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070D[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CTR_CLOSE_EM, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070E[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CTR_CLOSE_EM, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_070F[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0710[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0711[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0712[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0713[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0714[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0715[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0716[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0717[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0718[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_0719[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CTR_CLOSE_EM, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071A[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CTR_CLOSE_EM, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071B[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CTR_CLOSE_EM, CHR_i, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071C[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071D[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071E[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_n, CTR_ENDLINE };
static s16 scenario_text_071F[] = { CTR_EM_YELLOW, CHR_J, CHR_i, CHR_b, CHR_u, CHR_n, PCT_DASH, CHR_r, CHR_a, CHR_s, CHR_h, CHR_i, CHR_k, CHR_u, PCT_SPACE, CHR_i, CHR_k, CHR_i, CHR_t, CHR_e, PCT_SPACE, CHR_y, CHR_u, CHR_k, CHR_u, PCT_SPACE, CHR_n, CHR_o, PCT_SPACE, CHR_g, CHR_a, PCT_SPACE, CHR_i, CHR_c, CHR_h, CHR_i, CHR_b, CHR_a, CHR_n, CTR_CLOSE_EM, CTR_ENDLINE };



static s16 scenario_text_0800[] = { CTR_EM_YELLOW, CHR_D, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0801[] = { CTR_EM_YELLOW, CHR_D, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0802[] = { CTR_EM_YELLOW, CHR_D, CHR_a, PCT_SPACE, CHR_k, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0803[] = { CTR_EM_YELLOW, CHR_D, CHR_a, PCT_SPACE, CHR_k, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0804[] = { CTR_EM_YELLOW, CHR_D, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_a, CTR_ENDLINE };
static s16 scenario_text_0805[] = { CTR_EM_YELLOW, CHR_D, CHR_a, PCT_SPACE, CHR_k, CHR_a, CHR_r, CHR_a, CTR_CLOSE_EM, CTR_ENDLINE };



static s16 scenario_text_0900[] = { CTR_EM_YELLOW, CHR_G, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0901[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0902[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0903[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0904[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0905[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0906[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0907[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0908[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_0909[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090A[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090B[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090C[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090D[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090E[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_090F[] = { CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_1000[] = { CTR_EM_YELLOW, CHR_Y, CTR_CLOSE_EM, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1001[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CTR_CLOSE_EM, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1002[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1003[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1004[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1005[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1006[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CTR_CLOSE_EM, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1007[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CTR_CLOSE_EM, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1008[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CTR_CLOSE_EM, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1009[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CTR_CLOSE_EM, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100A[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CTR_CLOSE_EM, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100B[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100C[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100D[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100E[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_100F[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1010[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CTR_CLOSE_EM, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1011[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1012[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_a, CTR_ENDLINE };
static s16 scenario_text_1013[] = { CTR_EM_YELLOW, CHR_Y, CHR_u, CHR_m, CHR_e, PCT_SPACE, CHR_w, CHR_a, PCT_SPACE, CHR_h, CHR_i, CHR_t, CHR_o, CHR_t, CHR_s, CHR_u, PCT_SPACE, CHR_j, CHR_a, PCT_SPACE, CHR_n, CHR_a, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_1100[] = { CTR_EM_YELLOW, CHR_T, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1101[] = { CTR_EM_YELLOW, CHR_T, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1102[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1103[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1104[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1105[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1106[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1107[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1108[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CTR_CLOSE_EM, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1109[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CTR_CLOSE_EM, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110A[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110B[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110C[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CTR_CLOSE_EM, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110D[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110E[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_110F[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1110[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CTR_CLOSE_EM, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1111[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CTR_CLOSE_EM, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1112[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CTR_CLOSE_EM, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1113[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1114[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1115[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CTR_CLOSE_EM, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1116[] = { CTR_EM_YELLOW, CHR_T, CHR_e, PCT_SPACE, CHR_w, CHR_o, PCT_SPACE, CHR_n, CHR_o, CHR_b, CHR_a, CHR_s, CHR_e, CHR_b, CHR_a, PCT_SPACE, CHR_t, CHR_s, CHR_u, CHR_k, CHR_a, CHR_m, CHR_e, CHR_r, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_1200[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CTR_CLOSE_EM, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1201[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CTR_CLOSE_EM, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1202[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1203[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1204[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1205[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CTR_CLOSE_EM, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1206[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1207[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1208[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_c, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1209[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_120A[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_T, CHR_a, CHR_k, CHR_e, PCT_SPACE, CHR_a, PCT_SPACE, CHR_c, CHR_h, CHR_a, CHR_n, CHR_c, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };




static s16 scenario_text_1300[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1301[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1302[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1303[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1304[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1305[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1306[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1307[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1308[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, CTR_CLOSE_EM, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1309[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CTR_CLOSE_EM, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130A[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CTR_CLOSE_EM, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130B[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CTR_CLOSE_EM, CHR_b, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130C[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CTR_CLOSE_EM, CHR_a, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130D[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130E[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_130F[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, PCT_SPACE, CHR_s, CHR_o, PCT_SPACE, CHR_g, CHR_a, CHR_n, CHR_b, CHR_a, CHR_r, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };




static s16 scenario_text_1400[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CTR_CLOSE_EM, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1401[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CTR_CLOSE_EM, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1402[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CTR_CLOSE_EM, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1403[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CTR_CLOSE_EM, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1404[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CTR_CLOSE_EM, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1405[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CTR_CLOSE_EM, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1406[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CTR_CLOSE_EM, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1407[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CTR_CLOSE_EM, CHR_a, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1408[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CTR_CLOSE_EM, CHR_i, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_1409[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CTR_CLOSE_EM, CHR_d, CHR_e, CTR_ENDLINE };
static s16 scenario_text_140A[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CTR_CLOSE_EM, CHR_e, CTR_ENDLINE };
static s16 scenario_text_140B[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_A, CHR_k, CHR_i, CHR_r, CHR_a, CHR_m, CHR_e, CHR_n, CHR_a, CHR_i, CHR_d, CHR_e, CTR_CLOSE_EM, CTR_ENDLINE };


static s16 scenario_text_1500[] = { CTR_EM_YELLOW, CHR_K, CTR_CLOSE_EM, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1501[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CTR_CLOSE_EM, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1502[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CTR_CLOSE_EM, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1503[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CTR_CLOSE_EM, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1504[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CTR_CLOSE_EM, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1505[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CTR_CLOSE_EM, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1506[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CTR_CLOSE_EM, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1507[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, CTR_CLOSE_EM, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1508[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1509[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150A[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150B[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, CTR_CLOSE_EM, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150C[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CTR_CLOSE_EM, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150D[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CTR_CLOSE_EM, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150E[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, CTR_CLOSE_EM, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_150F[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CTR_CLOSE_EM, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1510[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CTR_CLOSE_EM, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1511[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CTR_CLOSE_EM, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1512[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CTR_CLOSE_EM, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1513[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, CTR_CLOSE_EM, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1514[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CTR_CLOSE_EM, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1515[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CTR_CLOSE_EM, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1516[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CTR_CLOSE_EM, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1517[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CTR_CLOSE_EM, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1518[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, CTR_CLOSE_EM, PCT_SPACE, CHR_y, CHR_o, CTR_ENDLINE };
static s16 scenario_text_1519[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CTR_CLOSE_EM, CHR_o, CTR_ENDLINE };
static s16 scenario_text_151A[] = { CTR_EM_YELLOW, CHR_K, CHR_u, CHR_c, CHR_h, CHR_i, CHR_b, CHR_u, CHR_e, PCT_SPACE, CHR_f, CHR_u, CHR_k, CHR_i, PCT_SPACE, CHR_s, CHR_a, CHR_a, PCT_SPACE, CHR_a, CHR_r, CHR_u, CHR_k, CHR_i, PCT_DASH, CHR_d, CHR_a, CHR_s, CHR_o, CHR_u, PCT_SPACE, CHR_y, CHR_o, CTR_CLOSE_EM, CTR_ENDLINE };



static s16 scenario_text_1600[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CTR_CLOSE_EM, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1601[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CTR_CLOSE_EM, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1602[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CTR_CLOSE_EM, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1603[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CTR_CLOSE_EM, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1604[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, CTR_CLOSE_EM, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1605[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CTR_CLOSE_EM, CHR_o, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1606[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CTR_CLOSE_EM, CHR_w, CTR_ENDLINE };
static s16 scenario_text_1607[] = { PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, PCT_SPACE, CTR_EM_YELLOW, CHR_G, CHR_o, CHR_i, CHR_n, CHR_g, PCT_SPACE, CHR_n, CHR_o, CHR_w, CTR_CLOSE_EM, CTR_ENDLINE };


"""

generate_scenario_calls(input_block)